title: Pengfan Chen's Homepage
page-top-title: Pengfan Chen
top-section-bg-text: High Energy Density Physics
home-subtitle: Pengfan Chen&ensp;|&ensp;陈鹏帆
copyright-text: '&copy; Pengfan Chen 2023-2026. All Rights Reserved.'